package postprocess

import (
	"math"
	"testing"
)

// TestUnclipBoxPaddleVsPaddleOCR compares the Go port of unclip+get_mini_boxes
// against the REAL PaddleOCR output (pyclipper JT_ROUND + cv2.minAreaRect),
// captured in /tmp/paddle_unclip_ref.py. PaddleOCR (via pyclipper) rounds
// offset coords to integers, so we compare within a tolerance that absorbs
// the sub-pixel round-vs-float difference (<1px at map scale, negligible after
// scaling to the original image).
func TestUnclipBoxPaddleVsPaddleOCR(t *testing.T) {
	// Each case: input quad (the minAreaRect box get_mini_boxes produces),
	// PaddleOCR reference final box + sside.
	cases := []struct {
		name    string
		in      [4][2]float64
		wantBox [4][2]float64
		wantS   float64
	}{
		// References generated by /tmp/paddle_unclip_ref2.py: realistic
		// minAreaRect boxes (true 90° rectangles) at various rotations, fed
		// through the real PaddleOCR unclip (pyclipper JT_ROUND) + get_mini_boxes.
		{
			"100x30 rot 0",
			[4][2]float64{{150, 185}, {250, 185}, {250, 215}, {150, 215}},
			[4][2]float64{{134, 169}, {266, 169}, {266, 231}, {134, 231}},
			62.0,
		},
		{
			"100x30 rot 20",
			[4][2]float64{{157.495, 167.812}, {252, 203}, {241.505, 231.188}, {147, 196}},
			[4][2]float64{{147.951, 146.297}, {272.828, 193.619}, {250.516, 252.501}, {125.638, 205.178}},
			62.967,
		},
		{
			"100x30 rot 45",
			[4][2]float64{{175, 154}, {245, 224}, {224, 245}, {154, 175}},
			[4][2]float64{{175, 132}, {267, 224}, {224, 267}, {132, 175}},
			60.811,
		},
		{
			"30x100 rot 70",
			[4][2]float64{{147, 203}, {241.505, 167.812}, {252, 196}, {157.495, 231.188}},
			[4][2]float64{{125.773, 192.241}, {250.849, 146.161}, {272.737, 205.571}, {147.661, 251.651}},
			63.313,
		},
	}
	const tol = 1.5 // px at map scale; absorbs pyclipper's int rounding vs float
	for _, c := range cases {
		expanded := UnclipBoxPaddle(c.in, 1.4)
		gotBox, gotS := GetMiniBoxes(expanded)
		// The winding/order of get_mini_boxes is deterministic, so compare
		// corner-by-corner after the same x-sort.
		gotSorted := sortCorners(gotBox)
		wantSorted := sortCorners(c.wantBox)
		for i := 0; i < 4; i++ {
			if math.Abs(gotSorted[i][0]-wantSorted[i][0]) > tol || math.Abs(gotSorted[i][1]-wantSorted[i][1]) > tol {
				t.Errorf("%s: corner %d got %v want %v (got %v want %v)",
					c.name, i, gotSorted[i], wantSorted[i], gotSorted, wantSorted)
			}
		}
		if math.Abs(gotS-c.wantS) > tol {
			t.Errorf("%s: sside got %.3f want %.3f", c.name, gotS, c.wantS)
		}
	}
}

func sortCorners(b [4][2]float64) [4][2]float64 {
	out := b
	for i := 1; i < 4; i++ {
		for j := i; j > 0 && (out[j-1][0] > out[j][0] || (out[j-1][0] == out[j][0] && out[j-1][1] > out[j][1])); j-- {
			out[j-1], out[j] = out[j], out[j-1]
		}
	}
	return out
}
